In [87]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')
%matplotlib inline

In [88]:
import os

In [89]:
os.getcwd()

'C:\\Users\\donal\\Desktop\\Python Programming Course'

In [90]:
movies=pd.read_csv('P4-Section6-Homework-Dataset.csv', encoding='latin1')

In [91]:
movies.head()

,Day of Week,Director,Genre,Movie Title,Release Date,Studio,Adjusted Gross ($mill),Budget ($mill),Gross ($mill),IMDb Rating,MovieLens Rating,Overseas ($mill),Overseas%,Profit ($mill),Profit%,Runtime (min),US ($mill),Gross % US
0,Friday,Brad Bird,action,Tomorrowland,22/05/2015,Buena Vista Studios,202.1,170.0,202.1,6.7,3.26,111.9,55.4,32.1,18.9,130,90.2,44.6
1,Friday,Scott Waugh,action,Need for Speed,14/03/2014,Buena Vista Studios,204.2,66.0,203.3,6.6,2.97,159.7,78.6,137.3,208.0,132,43.6,21.4
2,Friday,Patrick Hughes,action,The Expendables 3,15/08/2014,Lionsgate,207.1,100.0,206.2,6.1,2.93,166.9,80.9,106.2,106.2,126,39.3,19.1
3,Friday,"Phil Lord, Chris Miller",comedy,21 Jump Street,16/03/2012,Sony,208.8,42.0,201.6,7.2,3.62,63.1,31.3,159.6,380.0,109,138.4,68.7
4,Friday,Roland Emmerich,action,White House Down,28/06/2013,Sony,209.7,150.0,205.4,8.0,3.65,132.3,64.4,55.4,36.9,131,73.1,35.6

In [92]:
movies.describe()

,Budget ($mill),IMDb Rating,MovieLens Rating,Overseas%,Profit%,Runtime (min),US ($mill),Gross % US
count,608.000000,608.000000,608.000000,608.000000,608.000000,608.000000,608.000000,608.000000
mean,92.467928,6.923849,3.340378,57.698849,719.278783,117.781250,167.135197,42.301151
std,59.421407,0.925890,0.454071,12.334237,1942.807248,23.179122,92.465903,12.334237
min,0.600000,3.600000,1.490000,17.200000,7.700000,30.000000,0.000000,0.000000
25%,45.000000,6.375000,3.037500,49.900000,201.850000,100.000000,106.950000,33.700000
50%,80.000000,6.900000,3.365000,58.200000,338.550000,116.000000,141.700000,41.800000
75%,130.000000,7.600000,3.672500,66.300000,650.100000,130.250000,202.100000,50.100000
max,300.000000,9.200000,4.500000,100.000000,41333.300000,238.000000,760.500000,82.800000

In [93]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 608 entries, 0 to 607
Data columns (total 18 columns):
Day of Week               608 non-null object
Director                  608 non-null object
Genre                     608 non-null object
Movie Title               608 non-null object
Release Date              608 non-null object
Studio                    608 non-null object
Adjusted Gross ($mill)    608 non-null object
Budget ($mill)            608 non-null float64
Gross ($mill)             608 non-null object
IMDb Rating               608 non-null float64
MovieLens Rating          608 non-null float64
Overseas ($mill)          608 non-null object
Overseas%                 608 non-null float64
Profit ($mill)            608 non-null object
Profit%                   608 non-null float64
Runtime (min)             608 non-null int64
US ($mill)                608 non-null float64
Gross % US                608 non-null float64
dtypes: float64(7), int64(1), object(10)
memory usage: 85.6+ KB

In [ ]:
movies.DayOfWeek=movies.DayOfWeek.astype('category')
movies.Director=movies.Director.astype('category')
movies.Genre=movies.Genre.astype('category')
movies.MovieTitle=movies.MovieTitle.astype('category')
movies.ReleaseDate=movies.ReleaseDate.astype('category')
movies.Studio =movies.Studio .astype('category')
movies.AdjustedGrossMillions=movies.AdjustedGrossMillions.astype('category')
movies.GrossMillions=movies.GrossMillions.astype('category')
movies.OverseasMillions=movies.OverseasMillions.astype('category')
movies.ProfitMillions=movies.ProfitMillions.astype('category')

In [95]:
movies.columns

Index(['Day of Week', 'Director', 'Genre', 'Movie Title', 'Release Date',
       'Studio', 'Adjusted Gross ($mill)', 'Budget ($mill)', 'Gross ($mill)',
       'IMDb Rating', 'MovieLens Rating', 'Overseas ($mill)', 'Overseas%',
       'Profit ($mill)', 'Profit%', 'Runtime (min)', 'US ($mill)',
       'Gross % US'],
      dtype='object')

In [96]:
movies.columns=['DayOfWeek', 'Director', 'Genre', 'MovieTitle', 'ReleaseDate',
       'Studio', 'AdjustedGrossMillions', 'BudgetMillions', 'GrossMillions',
       'IMDbRating', 'MovieLensRating', 'OverseasMillions', 'Overseas%',
       'ProfitMillions', 'Profit%', 'RuntimeMin', 'USMillions',
       'Gross%US']

In [97]:
movies.head()

,DayOfWeek,Director,Genre,MovieTitle,ReleaseDate,Studio,AdjustedGrossMillions,BudgetMillions,GrossMillions,IMDbRating,MovieLensRating,OverseasMillions,Overseas%,ProfitMillions,Profit%,RuntimeMin,USMillions,Gross%US
0,Friday,Brad Bird,action,Tomorrowland,22/05/2015,Buena Vista Studios,202.1,170.0,202.1,6.7,3.26,111.9,55.4,32.1,18.9,130,90.2,44.6
1,Friday,Scott Waugh,action,Need for Speed,14/03/2014,Buena Vista Studios,204.2,66.0,203.3,6.6,2.97,159.7,78.6,137.3,208.0,132,43.6,21.4
2,Friday,Patrick Hughes,action,The Expendables 3,15/08/2014,Lionsgate,207.1,100.0,206.2,6.1,2.93,166.9,80.9,106.2,106.2,126,39.3,19.1
3,Friday,"Phil Lord, Chris Miller",comedy,21 Jump Street,16/03/2012,Sony,208.8,42.0,201.6,7.2,3.62,63.1,31.3,159.6,380.0,109,138.4,68.7
4,Friday,Roland Emmerich,action,White House Down,28/06/2013,Sony,209.7,150.0,205.4,8.0,3.65,132.3,64.4,55.4,36.9,131,73.1,35.6

In [98]:
 movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 608 entries, 0 to 607
Data columns (total 18 columns):
DayOfWeek                608 non-null object
Director                 608 non-null object
Genre                    608 non-null object
MovieTitle               608 non-null object
ReleaseDate              608 non-null object
Studio                   608 non-null object
AdjustedGrossMillions    608 non-null object
BudgetMillions           608 non-null float64
GrossMillions            608 non-null object
IMDbRating               608 non-null float64
MovieLensRating          608 non-null float64
OverseasMillions         608 non-null object
Overseas%                608 non-null float64
ProfitMillions           608 non-null object
Profit%                  608 non-null float64
RuntimeMin               608 non-null int64
USMillions               608 non-null float64
Gross%US                 608 non-null float64
dtypes: float64(7), int64(1), object(10)
memory usage: 85.6+ KB

In [99]:
movies.Studio.cat.categories

AttributeError: Can only use .cat accessor with a 'category' dtype

In [100]:
movies2= movies[(movies.Genre=='action')|(movies.Genre=='adventure')|(movies.Genre=='animation')|(movies.Genre=="Drama")]

In [101]:
movies3=movies2[(movies2.Studio=="Buene Vista Studio")|(movies2.Studio=="Fox")| (movies2.Studio=='Paramount Pictures')| (movies2.Studio=='Universal')| (movies2.Studio=='Sony')| (movies2.Studio=='WB ')]

In [102]:
print(movies2.Genre.unique())
print(movies3.Studio.unique())
print(len(movies))

['action' 'adventure' 'animation']
['Sony' 'Universal' 'Paramount Pictures' 'Fox']
608

In [103]:
# Plot the boxsplots
ax = sns._(data=_, x='_', y='_', orient='v', color='lightgray', showfliers=False)
plt.setp(ax.artists, alpha=0.5)

# Add in points to show each observation
_.stripplot(x='_', y='_', data=_, jitter=True, size=6, linewidth=0, hue = 'Studio', alpha=0.7)

ax.axes.set_title('_',fontsize=30)
ax.set_xlabel('_',fontsize=20)
ax.set_ylabel('_',fontsize=20)

# Define where to place the legend
ax.legend(bbox_to_anchor=(1.05, 1), loc=2, borderaxespad=0.)

AttributeError: module 'seaborn' has no attribute '_'